### ISSUE TITLE
mouseup event not triggered if result option is dragged

### ISSUE THREAD

**Issue by ocarreterom** [github/auto-complete-element#18]
If a result option is dragged outside of `<ul id="users-popup"></ul>` the  `this.mouseDown` flag is set to `true` but it never turns back to `false` (unless you click any option from the list), so the popup can not be closed on input `blur`.

https://github.com/github/auto-complete-element/blob/466c1f68473a0cee560acbf4971d84111e34d663/src/autocomplete.js#L106-L109

## Test
1. Type something
2. Click and drag an option outside the results list
3. Try to close the popup without selecting any option from the results list

## Possible solution
Change `mousedown`/`mouseup` for `mouseenter`/`mouseleave`?

**Comment by muan** [comment]
This is fixed and released in `v1.0.2`. Thanks for the report!
