### ISSUE TITLE
The combobox doesn't scroll when navigating

### ISSUE THREAD

**Issue by bnjamin** [github/auto-complete-element#24]
After PR #15 the combobox no longer scrolls when navigating with the arrow keys.

I've made a small example here https://auto-complete-scroll.glitch.me it is the example from this repo, but where I've added a `height: 45px; overflow-y: auto;` styling to the `ul` element.

The problem is that the [select method](https://github.com/github/auto-complete-element/blob/6d84ea75aaab443fbe02859dc404b063975669f0/src/autocomplete.js#L67) in `autocomplete.js` is no longer called when navigating, so the `scrollTo` function is never called.

It can be fixed by either moving the scroll functionality to the [combobox-nav](https://github.com/github/combobox-nav) project instead, or have the combo-box fire an `combobox-navigation` event and then listen for that and perform the necessary scrolling.

If one of the proposed methods are suitable, I can submit a PR.

**Comment by muan** [comment]
Good catch! 

I think scroll should happen in `combobox-nav` (so `scroll.js` should be moved there), and the unused function here should be cleaned up.

**Comment by muan** [comment]
Fix is out in https://github.com/github/auto-complete-element/releases/tag/v1.0.3. Thanks again for investigating and fixing this.
